kind: pipeline
type: docker
name: default

steps:
- name: Deploy Cocoa Pod
  image: gaetan/cocoapods
  pull: if-not-exists
  commands:
  - pod trunk push CleverPush.podspec
  environment:
    COCOAPODS_TRUNK_TOKEN:
      from_secret: COCOAPODS_TRUNK_TOKEN

trigger:
  branch:
  - CP-1965_ci-deployment

#trigger:
#  ref:
#  - refs/head/master
#  - refs/tag/*
