name: CI Deploy

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Deploy new version to CocoaPods
    runs-on: macos-12

    steps:
      - name: Checkout SDK
        uses: actions/checkout@v3
      - name: Pod Deploy
        run: pod trunk push CleverPush.podspec --allow-warnings --verbose
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      - name: Generate Changelog
        run: |
          sed -n "/$GITHUB_REF_NAME/,/^$/{/^$/q;p;}" CHANGELOG.md > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          token: ${{ secrets.RELEASE_TOKEN }}
