name: CI Lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Lints CocoaPods
    runs-on: macos-14

    steps:
      - name: Checkout SDK
        uses: actions/checkout@v3
      - name: Pod Lint
        run: pod lib lint CleverPush.podspec --allow-warnings --verbose
